import { describe,expect,it } from 'vitest'
import { AgentDatabase } from '../src/agent/database.js'
import { AppStore, requireAppConnector, runWithAppScope } from '../src/agent/apps/store.js'
import { PolicyStore } from '../src/agent/policies/store.js'
import { requireCurrentSessionConnectorBinding } from '../src/agent/session-connector-access.js'
const actor={oid:'owner',tenantId:'tenant',displayName:'Owner',roles:['Papyrus.System.Owner' as const],groups:[],source:'entra' as const}
function setup(){const db=new AgentDatabase(':memory:');db.sqlite.prepare(`INSERT INTO agent_integrations(id,catalog_id,name,integration_class,authority,risk,state,scope,settings_json,health,created_by_oid,created_at,updated_at,version) VALUES('connector','github','GitHub','connector','bidirectional','low','active','workspace','{}','healthy','owner','2026','2026',1)`).run();const apps=new AppStore(db),app=apps.create('test','owner','session-a'),release=apps.candidate(app.id,'src','<html></html>'),policies=new PolicyStore(db);policies.approve(apps.requestPublish(app.id,release.id,'owner'),actor,(k,r,v,b)=>apps.apply(k,r,v,b,'owner'));return{db,apps,app,release,policies}}
describe('app runtime connector enforcement',()=>{
 it('does not accept deployment integration or session authority as an app grant',()=>{const {db,app,release}=setup();try{expect(()=>requireAppConnector(db,app.id,'connector','readGithubFile','owner',release.id)).toThrow(/granted/)}finally{db.close()}})
 it('checks the exact integration at low-level dispatch and honors revocation',()=>{const {db,apps,app,release,policies}=setup();try{policies.approve(apps.requestGrant(app.id,'connector',['readGithubFile'],'owner'),actor,(k,r,v,b)=>apps.apply(k,r,v,b,'owner'));expect(runWithAppScope({db,appId:app.id,releaseId:release.id,actorOid:'owner',operation:'readGithubFile',integrationId:'connector'},()=>requireCurrentSessionConnectorBinding('connector').id)).toBe('connector');expect(()=>runWithAppScope({db,appId:app.id,releaseId:release.id,actorOid:'owner',operation:'readGithubFile',integrationId:'other'},()=>requireCurrentSessionConnectorBinding('connector'))).toThrow();apps.revoke(app.id,'connector','owner');expect(()=>requireAppConnector(db,app.id,'connector','readGithubFile','owner',release.id)).toThrow()}finally{db.close()}})
 it('applies app policies to existing grants',()=>{const {db,apps,app,release,policies}=setup();try{policies.approve(apps.requestGrant(app.id,'connector',['readGithubFile'],'owner'),actor,(k,r,v,b)=>apps.apply(k,r,v,b,'owner'));policies.create('deny app read',[{kind:'deny',field:'operation',values:['readGithubFile']}],[{scope:'app',resourceId:app.id}],'owner');expect(()=>requireAppConnector(db,app.id,'connector','readGithubFile','owner',release.id)).toThrow(/DENY/)}finally{db.close()}})
})
