export interface TextPdfInput {
  title?: string
  body?: string
}

const PAGE_WIDTH = 612
const PAGE_HEIGHT = 792
const BODY_START_Y = 700
const BODY_LINE_HEIGHT = 14
const BODY_LINES_PER_PAGE = 44
const BODY_WRAP = 86

export function normalizePdfFilename(value: string | undefined): string {
  const raw = (value ?? 'document.pdf').trim().replace(/\\/g, '/').split('/').at(-1) ?? 'document.pdf'
  const cleaned = raw.replace(/[^A-Za-z0-9._-]/g, '_').replace(/^\.+/, '').slice(0, 160) || 'document'
  return cleaned.toLowerCase().endsWith('.pdf') ? cleaned : `${cleaned}.pdf`
}

export function createTextPdf(input: TextPdfInput = {}): Buffer {
  const title = ascii(input.title?.trim() || 'Papyrus Document')
  const body = ascii(input.body?.trim() || 'Generated by Papyrus.')
  const bodyLines = wrapText(body, BODY_WRAP)
  const pages = chunk(bodyLines.length ? bodyLines : [''], BODY_LINES_PER_PAGE)
  const pageCount = Math.max(1, pages.length)
  const fontId = 3 + pageCount * 2
  const objects = new Map<number, string>()

  const pageIds = Array.from({ length: pageCount }, (_, index) => 3 + index * 2)
  objects.set(1, '<< /Type /Catalog /Pages 2 0 R >>')
  objects.set(2, `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(' ')}] /Count ${pageCount} >>`)

  for (let index = 0; index < pageCount; index += 1) {
    const pageId = 3 + index * 2
    const contentId = pageId + 1
    const stream = pageStream(title, pages[index] ?? [''], index)
    objects.set(pageId, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${contentId} 0 R >>`)
    objects.set(contentId, `<< /Length ${Buffer.byteLength(stream, 'ascii')} >>\nstream\n${stream}\nendstream`)
  }

  objects.set(fontId, '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>')

  let output = '%PDF-1.4\n'
  const offsets = new Array<number>(fontId + 1).fill(0)
  for (let id = 1; id <= fontId; id += 1) {
    const object = objects.get(id)
    if (!object) throw new Error(`Missing PDF object ${id}`)
    offsets[id] = Buffer.byteLength(output, 'ascii')
    output += `${id} 0 obj\n${object}\nendobj\n`
  }

  const xrefOffset = Buffer.byteLength(output, 'ascii')
  output += `xref\n0 ${fontId + 1}\n`
  output += '0000000000 65535 f \n'
  for (let id = 1; id <= fontId; id += 1) {
    output += `${String(offsets[id]).padStart(10, '0')} 00000 n \n`
  }
  output += `trailer\n<< /Size ${fontId + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`
  return Buffer.from(output, 'ascii')
}

function pageStream(title: string, lines: string[], pageIndex: number): string {
  const commands: string[] = ['BT']
  if (pageIndex === 0) {
    commands.push('/F1 22 Tf')
    commands.push('1 0 0 1 72 744 Tm')
    commands.push(`(${pdfString(title)}) Tj`)
  } else {
    commands.push('/F1 9 Tf')
    commands.push('1 0 0 1 72 756 Tm')
    commands.push(`(${pdfString(title)} - continued) Tj`)
  }

  commands.push('/F1 11 Tf')
  lines.forEach((line, index) => {
    const y = BODY_START_Y - index * BODY_LINE_HEIGHT
    commands.push(`1 0 0 1 72 ${y} Tm`)
    commands.push(`(${pdfString(line)}) Tj`)
  })
  commands.push('ET')
  return commands.join('\n')
}

function wrapText(value: string, width: number): string[] {
  const output: string[] = []
  for (const paragraph of value.replace(/\r\n?/g, '\n').split('\n')) {
    if (!paragraph.trim()) {
      output.push('')
      continue
    }
    let line = ''
    for (const word of paragraph.trim().split(/\s+/)) {
      if (!line) {
        line = word
        continue
      }
      if (line.length + 1 + word.length <= width) {
        line += ` ${word}`
        continue
      }
      output.push(line)
      line = word
      while (line.length > width) {
        output.push(line.slice(0, width))
        line = line.slice(width)
      }
    }
    if (line) output.push(line)
  }
  return output
}

function chunk<T>(items: T[], size: number): T[][] {
  const output: T[][] = []
  for (let index = 0; index < items.length; index += size) output.push(items.slice(index, index + size))
  return output.length ? output : [[]]
}

function pdfString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

function ascii(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^\x09\x0A\x0D\x20-\x7E]/g, '?')
    .replace(/\t/g, '    ')
}
