import { useCallback, useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { ROLES, type AdminOverview, type Principal, type Role } from '@papyrus/contracts'
import { addMcpServer, addUserRole, adminOverview, assignWorkspace, createWorkspaceAdmin, grantTool, revokeToolGrant, revokeUserSessions, setMcpServerEnabled } from './api.js'

export function AdminView({ me }: { me: Principal }) {
  const [data, setData] = useState<AdminOverview>()
  const [error, setError] = useState<string>()
  const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { setData(await adminOverview()) }, [])
  useEffect(() => { void load().catch(show) }, [load])
  function show(cause: unknown) { setError(cause instanceof Error ? cause.message : 'Administrative request failed') }
  const act = async (operation: () => Promise<unknown>) => { setBusy(true); setError(undefined); try { await operation(); await load() } catch (cause) { show(cause) } finally { setBusy(false) } }
  if (!data) return <div className="empty">Loading deployment administration…</div>
  const allowedRoles = me.roles.includes('Owner') ? ROLES : ROLES.filter((role) => role !== 'Owner' && role !== 'Admin')
  return <div className="admin-view">
    {error && <div className="error">{error}<button onClick={() => setError(undefined)}>×</button></div>}
    <section className="admin-summary">
      <AdminPanel title="Deployment"><dl className="facts"><Fact label="Profile" value={data.deployment.profile} /><Fact label="Mode" value={data.deployment.mode} /><Fact label="Origin" value={data.deployment.publicOrigin} /><Fact label="OIDC" value={yes(data.deployment.oidcConfigured)} /><Fact label="mTLS" value={yes(data.deployment.mtlsConfigured)} /><Fact label="Gateway" value={yes(data.deployment.gatewayConfigured)} /></dl></AdminPanel>
      <AdminPanel title="License"><dl className="facts"><Fact label="Required" value={yes(data.deployment.licenseRequired)} /><Fact label="Status" value={data.license.valid ? 'VALID' : 'NOT ACTIVE'} /><Fact label="Deployment" value={data.license.deploymentId.slice(0, 16)} /></dl></AdminPanel>
    </section>
    <AdminPanel title="Identity and roles"><div className="admin-list">{data.users.map((user) => <article key={user.id}><div><strong>{user.displayName}</strong><span>{user.email ?? user.externalId}</span><span>{user.roles.join(' · ') || 'No role'} · {user.authMethod}</span></div><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void act(() => addUserRole(user.id, String(form.get('role')) as Role)) }}><select name="role">{allowedRoles.map((role) => <option key={role}>{role}</option>)}</select><button className="secondary" disabled={busy}>Add role</button><button type="button" className="danger" disabled={busy} onClick={() => void act(() => revokeUserSessions(user.id))}>Revoke sessions</button></form></article>)}</div></AdminPanel>
    <AdminPanel title="Workspace assignments"><AdminForm onSubmit={(form) => act(() => createWorkspaceAdmin(String(form.get('name')), String(form.get('description') ?? '')))}><input name="name" required maxLength={256} placeholder="Workspace name" /><input name="description" maxLength={2000} placeholder="Description" /><button className="primary" disabled={busy}>Create workspace</button></AdminForm><AdminForm onSubmit={(form) => act(() => assignWorkspace(String(form.get('principalId')), String(form.get('resourceId'))))}><select name="principalId">{data.users.map((user) => <option value={user.id} key={user.id}>{user.displayName}</option>)}</select><select name="resourceId">{data.workspaces.map((workspace) => <option value={workspace.id} key={workspace.id}>{workspace.name}</option>)}</select><button className="primary" disabled={busy || !data.workspaces.length}>Assign user</button></AdminForm><div className="admin-list compact">{data.workspaces.map((workspace) => <article key={workspace.id}><div><strong>{workspace.name}</strong><span>{workspace.description || 'No description'}</span><span>{workspace.assignedUserIds.length} assigned users</span></div></article>)}</div></AdminPanel>
    <AdminPanel title="MCP servers and tool grants"><AdminForm onSubmit={(form) => act(() => addMcpServer(String(form.get('name')), String(form.get('endpoint'))))}><input name="name" required maxLength={256} placeholder="Server name" /><input name="endpoint" type="url" required maxLength={2048} placeholder="https://mcp.internal/rpc" /><button className="primary" disabled={busy}>Add server</button></AdminForm><div className="admin-list compact">{data.mcpServers.map((server) => <article key={server.id}><div><strong>{server.name}</strong><span>{server.endpoint}</span><span>{server.transport} · {server.enabled ? 'enabled' : 'disabled'}</span></div><button className={server.enabled ? 'danger' : 'secondary'} disabled={busy} onClick={() => void act(() => setMcpServerEnabled(server.id, !server.enabled))}>{server.enabled ? 'Disable' : 'Enable'}</button></article>)}</div><AdminForm onSubmit={(form) => act(() => grantTool(String(form.get('workspaceId')), String(form.get('mcpServerId')), String(form.get('toolName'))))}><select name="workspaceId">{data.workspaces.map((workspace) => <option value={workspace.id} key={workspace.id}>{workspace.name}</option>)}</select><select name="mcpServerId">{data.mcpServers.map((server) => <option value={server.id} key={server.id}>{server.name}</option>)}</select><input name="toolName" required maxLength={256} placeholder="Tool name, e.g. browser_read" /><button className="primary" disabled={busy || !data.workspaces.length || !data.mcpServers.length}>Grant tool</button></AdminForm><div className="grant-list">{data.toolGrants.map((grant) => <div key={grant.id}><span>{name(data.workspaces, grant.workspaceId)} → {name(data.mcpServers, grant.mcpServerId)} / <strong>{grant.toolName}</strong></span><button className="danger" disabled={busy} onClick={() => void act(() => revokeToolGrant(grant.id))}>Revoke</button></div>)}</div></AdminPanel>
    <section className="admin-summary"><AdminPanel title="Runtime catalog"><div className="admin-list compact">{data.runtimeProfiles.map((runtime) => <article key={runtime.id}><div><strong>{runtime.label}</strong><span>{runtime.command} {runtime.args.join(' ')}</span><a href={runtime.source} target="_blank" rel="noreferrer">Source profile</a></div></article>)}{data.agents.map((agent) => <article key={`agent-${agent.id}`}><div><strong>{agent.id}</strong><span>profile {agent.profile}{agent.isDefault ? ' · default' : ''}</span></div></article>)}</div></AdminPanel><AdminPanel title="Browser connectors"><div className="admin-list compact">{data.connectors.length ? data.connectors.map((connector) => <article key={connector.id}><div><strong>{connector.label}</strong><span>{connector.package}</span><span>{Object.entries(connector.operations).map(([operation, action]) => `${operation}: ${action}`).join(' · ')}</span></div></article>) : <div className="empty">No browser connector is enabled in deployment configuration.</div>}</div></AdminPanel></section>
  </div>
}

function AdminPanel({ title, children }: { title: string; children: ReactNode }) { return <article className="panel admin-panel"><div className="panel-head"><h2>{title}</h2></div>{children}</article> }
function AdminForm({ onSubmit, children }: { onSubmit: (form: FormData) => Promise<unknown>; children: ReactNode }) { return <form className="admin-form" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; void onSubmit(new FormData(form)).then(() => form.reset()) }}>{children}</form> }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div> }
function yes(value: boolean) { return value ? 'CONFIGURED' : 'NOT CONFIGURED' }
function name(items: Array<{ id: string; name: string }>, id: string) { return items.find((item) => item.id === id)?.name ?? id.slice(0, 8) }
