import { useCallback, useEffect, useState, type ReactNode } from 'react'
import { ROLES, type AdminOverview, type Principal, type Role } from '@papyrus/contracts'
import { addMcpServer, addUserRole, adminOverview, revokeUserSessions, setMcpServerEnabled } from './api.js'
import { SelectField } from './SelectField.js'

type AdminTab = 'deployment' | 'identity' | 'integrations' | 'runtimes'

export function AdminView({ me }: { me: Principal }) {
  const [data, setData] = useState<AdminOverview>()
  const [tab, setTab] = useState<AdminTab>('deployment')
  const [error, setError] = useState<string>()
  const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { setData(await adminOverview()) }, [])
  useEffect(() => { void load().catch(show) }, [load])
  useEffect(() => { const connected = (event: MessageEvent) => { if (event.origin === window.location.origin && event.data?.type === 'papyrus:mcp-connected') void load() }; window.addEventListener('message', connected); return () => window.removeEventListener('message', connected) }, [load])
  function show(cause: unknown) { setError(cause instanceof Error ? cause.message : 'Administrative request failed') }
  const act = async (operation: () => Promise<unknown>) => { setBusy(true); setError(undefined); try { await operation(); await load() } catch (cause) { show(cause) } finally { setBusy(false) } }
  if (!data) return <div className="empty">Loading deployment administration…</div>
  const allowedRoles = me.roles.includes('Owner') ? ROLES : ROLES.filter((role) => role !== 'Owner' && role !== 'Admin')
  return <div className="admin-view">
    {error && <div className="error">{error}<button onClick={() => setError(undefined)}>×</button></div>}
    <div className="admin-tabs" role="tablist">{(['deployment', 'identity', 'integrations', 'runtimes'] as AdminTab[]).map((item) => <button key={item} className={tab === item ? 'active' : ''} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === 'deployment' && <section className="admin-summary"><AdminPanel title="Deployment"><dl className="facts"><Fact label="Profile" value={data.deployment.profile} /><Fact label="Topology" value="ON-PREMISES" /><Fact label="Origin" value={data.deployment.publicOrigin} /><Fact label="Authentication" value={authenticationLabel(data.deployment.authentication)} /><Fact label="Gateway" value={yes(data.deployment.gatewayConfigured)} /></dl></AdminPanel><AdminPanel title="License"><dl className="facts"><Fact label="Required" value={yes(data.deployment.licenseRequired)} /><Fact label="Status" value={data.license.valid ? 'VALID' : 'NOT ACTIVE'} /><Fact label="Deployment" value={data.license.deploymentId.slice(0, 16)} /></dl></AdminPanel></section>}
    {tab === 'identity' && <AdminPanel title="Identity and roles"><div className="admin-list">{data.users.map((user) => { const eligibleRoles = allowedRoles.filter((role) => !user.roles.includes(role)); return <article key={user.id}><div><strong>{user.displayName}</strong><span>{user.email ?? authenticationLabel(user.authMethod)}</span><span>{user.roles.join(' · ') || 'No role'} · {authenticationLabel(user.authMethod)}</span></div><form onSubmit={(event) => { event.preventDefault(); const role = new FormData(event.currentTarget).get('role'); if (typeof role === 'string' && role) void act(() => addUserRole(user.id, role as Role)) }}><SelectField name="role" label="Eligible role" placeholder="Choose a role" options={eligibleRoles.map((role) => ({ value: role, label: role }))} /><button className="secondary" disabled={busy || eligibleRoles.length === 0}>Add role</button><button type="button" className="danger" disabled={busy} onClick={() => void act(() => revokeUserSessions(user.id))}>Revoke sessions</button></form></article> })}</div></AdminPanel>}
    {tab === 'integrations' && <section className="admin-summary"><AdminPanel title="MCP servers"><form className="admin-form mcp-register" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); setBusy(true); setError(undefined); void addMcpServer(String(values.get('name')), String(values.get('endpoint'))).then((result) => { form.reset(); if (result.authorizationUrl) window.open(result.authorizationUrl, 'papyrus-mcp-oauth', 'popup,width=720,height=820'); return load() }).catch(show).finally(() => setBusy(false)) }}><input name="name" required maxLength={256} placeholder="Server name" /><input name="endpoint" type="url" required maxLength={2048} placeholder="https://mcp.internal/rpc" /><button className="primary" disabled={busy}>{busy ? 'Discovering…' : 'Connect server'}</button></form><div className="admin-list compact">{data.mcpServers.map((server) => <article key={server.id}><div><strong>{server.name}</strong><span>{server.endpoint}</span><span>{server.oauthStatus === 'connected' ? `OAuth connected · ${server.oauthIssuer}` : server.oauthStatus === 'authorization_required' ? 'Waiting for OAuth authorization' : server.oauthStatus === 'error' ? server.oauthError : 'No OAuth challenge · direct connection'} </span></div><button className={server.enabled ? 'danger' : 'secondary'} disabled={busy || server.oauthStatus === 'authorization_required'} onClick={() => void act(() => setMcpServerEnabled(server.id, !server.enabled))}>{server.enabled ? 'Disable' : 'Enable'}</button></article>)}</div><p className="admin-note">Papyrus discovers protected-resource metadata, dynamically registers an OAuth client, and completes authorization-code + PKCE before a protected remote server becomes available.</p></AdminPanel><AdminPanel title="Browser connectors"><div className="admin-list compact">{data.connectors.length ? data.connectors.map((connector) => <article key={connector.id}><div><strong>{connector.label}</strong><span>{connector.package}</span><span>{Object.entries(connector.operations).map(([operation, action]) => `${operation}: ${action}`).join(' · ')}</span></div></article>) : <div className="empty">No browser connector is enabled in deployment configuration.</div>}</div></AdminPanel></section>}
    {tab === 'runtimes' && <AdminPanel title="Configured runtimes"><div className="admin-list runtime-list">{data.agents.map((agent) => { const profile = data.runtimeProfiles.find((item) => item.id === agent.profile); return <article key={agent.id}><div><strong>{profile?.label ?? agent.id}{agent.isDefault ? ' · Default' : ''}</strong><span>{agent.id} · {profile ? `${profile.command} ${profile.args.join(' ')}` : `profile ${agent.profile}`}</span>{profile && <a href={profile.source} target="_blank" rel="noreferrer">Source profile</a>}</div><span className={`pill ${agent.isDefault ? 'completed' : 'pending'}`}>{agent.isDefault ? 'active default' : 'configured'}</span></article> })}</div><p className="admin-note">Catalog profiles define launch metadata; this list shows only runtimes configured for this deployment.</p></AdminPanel>}
  </div>
}

function AdminPanel({ title, children }: { title: string; children: ReactNode }) { return <article className="panel admin-panel"><div className="panel-head"><h2>{title}</h2></div>{children}</article> }
function Fact({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div> }
function yes(value: boolean) { return value ? 'CONFIGURED' : 'NOT CONFIGURED' }
function authenticationLabel(value: Principal['authMethod'] | AdminOverview['deployment']['authentication']) { return ({ oidc: 'ORGANIZATIONAL OIDC', mtls: 'CAC/PIV MTLS', 'trusted-proxy': 'TRUSTED IDENTITY PROXY', 'loopback-development': 'LOOPBACK DEVELOPMENT', development: 'LOOPBACK DEVELOPMENT' } as Record<string, string>)[value] ?? String(value).toUpperCase() }
