import { useEffect, useState } from 'react'
import { POLICY_SCOPES, type NamedPolicy, type PolicyScope, type PortalPrincipal } from '@papyrus/contracts'
import { appRequest } from './AppBuilder.js'
export function PoliciesView({actor}:{actor:PortalPrincipal}){
  const [policies,setPolicies]=useState<NamedPolicy[]>([]),[name,setName]=useState(''),[rules,setRules]=useState('[\n  {"kind":"approval"}\n]'),[scope,setScope]=useState<PolicyScope>('session'),[resource,setResource]=useState(''),[selected,setSelected]=useState<NamedPolicy>(),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const canManage=actor.roles.includes('Papyrus.System.Owner')||actor.roles.includes('Papyrus.Security.Manage')&&actor.roles.includes('Papyrus.Action.Approve')
  const refresh=()=>appRequest<{policies:NamedPolicy[]}>('/api/policies').then(v=>setPolicies(v.policies))
  useEffect(()=>{void refresh().catch(e=>setError(String(e)))},[])
  return <section className="app-workbench"><h2>Policies</h2><p>Named deterministic restrictions apply at dispatch. Policies can restrict existing access; they never grant it.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{canManage&&<form onSubmit={e=>{e.preventDefault();setError('');try{const data={name,rules:JSON.parse(rules),attachments:[{scope,resourceId:scope==='workspace'?'*':resource}],...(selected?{version:selected.version}:{})};void appRequest<{changeId?:string}>(selected?`/api/policies/${selected.id}`:'/api/policies',selected?'PUT':'POST',data).then(async v=>{setNotice(v.changeId?'Change requires Governance approval. The current restrictions remain active.':'Restriction saved.');setSelected(undefined);await refresh()}).catch(e=>setError(String(e)))}catch(e){setError(String(e))}}}><label>Name<input required value={name} disabled={!!selected} onChange={e=>setName(e.target.value)}/></label><label>Attach to<select value={scope} onChange={e=>setScope(e.target.value as PolicyScope)}>{POLICY_SCOPES.map(s=><option key={s}>{s}</option>)}</select></label>{scope!=='workspace'&&<label>Resource ID<input required value={resource} onChange={e=>setResource(e.target.value)}/></label>}<label style={{width:'100%'}}>Rules<textarea className="policy-editor" value={rules} onChange={e=>setRules(e.target.value)}/></label><p>Supported rules: allow/deny sets with a field and values; numeric limits with a field and maximum; approval requirements. Removing a restriction or attachment requires approval.</p><button>{selected?'Save change':'Create policy'}</button>{selected&&<button type="button" onClick={()=>setSelected(undefined)}>Cancel</button>}</form>}{policies.map(p=><article key={p.id} className="policy-card"><h3>{p.name} <small>v{p.version}</small></h3><p>{p.attachments.map(a=>`${a.scope}: ${a.resourceId}`).join(' · ')}</p><pre>{JSON.stringify(p.rules,null,2)}</pre>{canManage&&<button onClick={()=>{setSelected(p);setName(p.name);setRules(JSON.stringify(p.rules,null,2));setScope(p.attachments[0]?.scope??'workspace');setResource(p.attachments[0]?.resourceId??'*')}}>Edit policy</button>}</article>)}</section>
}
export function AppGovernance(){
  const [changes,setChanges]=useState<Record<string,unknown>[]>([]),[error,setError]=useState('')
  const refresh=()=>appRequest<{changes:Record<string,unknown>[]}>('/api/governed-changes').then(v=>setChanges(v.changes.filter(c=>c.state==='pending')))
  useEffect(()=>{void refresh().catch(e=>setError(String(e)))},[])
  return <section className="app-workbench"><h2>App and policy approvals</h2>{error&&<p role="alert">{error}</p>}{!changes.length&&<p>No pending app or policy changes.</p>}{changes.map(c=><article className="policy-card" key={String(c.id)}><h3>{String(c.kind)}</h3><p>Resource: {String(c.resource_id)} · Requested by {String(c.requested_by)}</p><pre>{JSON.stringify(c.body,null,2)}</pre><p>Reviewed digest: {String(c.digest)}</p><button onClick={()=>{void appRequest(`/api/governed-changes/${c.id}/approve`,'POST',{}).then(refresh).catch(e=>setError(String(e)))}}>Approve this exact change</button></article>)}</section>
}
