import { createOpenAI } from '@ai-sdk/openai'
import { Output, generateText, jsonSchema, streamText, tool } from 'ai'
import { type ScaffoldProject, scaffoldProject, scaffoldToolDescriptions } from './scaffolds.js'

export interface ModelProviderConfig {
  provider: 'cloudflare-messages' | 'openai-compatible' | 'demo'
  baseURL: string
  apiKey: string
  model: string
}

export interface ModelMessage {
  role: 'user' | 'assistant'
  content: string
}

export interface GeneratedProject {
  title: string
  summary: string
  files: Array<{ path: string; content: string; language?: string }>
  entrypoint: string
  template: 'react-ts' | 'react' | 'vanilla-ts' | 'vanilla' | 'static' | 'vue' | 'svelte'
}

interface ProjectChanges {
  title: string
  summary: string
  files: Array<{ path: string; content: string; language?: string }>
}

const projectChangesSchema = jsonSchema<ProjectChanges>({
  type: 'object',
  additionalProperties: false,
  required: ['title', 'summary', 'files'],
  properties: {
    title: { type: 'string' },
    summary: { type: 'string' },
    files: {
      type: 'array',
      minItems: 1,
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['path', 'content'],
        properties: {
          path: { type: 'string' },
          content: { type: 'string' },
          language: { type: 'string' },
        },
      },
    },
  },
})

const emptyToolInput = jsonSchema<Record<string, never>>({
  type: 'object',
  additionalProperties: false,
  properties: {},
})

const scaffoldTools = {
  scaffold_webapp: tool({
    description: scaffoldToolDescriptions.scaffold_webapp,
    inputSchema: emptyToolInput,
    execute: async () => scaffoldProject('scaffold_webapp'),
  }),
  scaffold_cli_ts: tool({
    description: scaffoldToolDescriptions.scaffold_cli_ts,
    inputSchema: emptyToolInput,
    execute: async () => scaffoldProject('scaffold_cli_ts'),
  }),
  scaffold_cli_py: tool({
    description: scaffoldToolDescriptions.scaffold_cli_py,
    inputSchema: emptyToolInput,
    execute: async () => scaffoldProject('scaffold_cli_py'),
  }),
  scaffold_api_rust: tool({
    description: scaffoldToolDescriptions.scaffold_api_rust,
    inputSchema: emptyToolInput,
    execute: async () => scaffoldProject('scaffold_api_rust'),
  }),
  scaffold_api_zig: tool({
    description: scaffoldToolDescriptions.scaffold_api_zig,
    inputSchema: emptyToolInput,
    execute: async () => scaffoldProject('scaffold_api_zig'),
  }),
}

function demoProject(): GeneratedProject {
  return {
    title: 'UAS Marketplace',
    summary: 'Runnable marketplace starter generated by the demo provider.',
    entrypoint: '/src/main.tsx',
    template: 'react-ts',
    files: [
      {
        path: '/package.json',
        language: 'json',
        content: JSON.stringify({
          scripts: { start: 'vite' },
          dependencies: {
            '@vitejs/plugin-react': 'latest',
            vite: 'latest',
            react: 'latest',
            'react-dom': 'latest',
          },
          devDependencies: {},
        }),
      },
      {
        path: '/index.html',
        language: 'html',
        content: '<div id="root"></div><script type="module" src="/src/main.tsx"></script>',
      },
      {
        path: '/src/main.tsx',
        language: 'tsx',
        content:
          "import React from 'react';import{createRoot}from'react-dom/client';import'./styles.css';createRoot(document.getElementById('root')!).render(<main><h1>UAS Marketplace</h1><p>Discover and evaluate commercial capabilities.</p></main>);",
      },
      {
        path: '/src/styles.css',
        language: 'css',
        content:
          'body{font-family:system-ui;margin:0;padding:3rem;background:#f7f7f7}main{max-width:900px;margin:auto;background:white;padding:3rem;border:2px solid #111}',
      },
    ],
  }
}

export async function generateModelProject(
  config: ModelProviderConfig,
  input: {
    system: string
    messages: ModelMessage[]
    maxOutputTokens?: number
    existingFiles?: Array<{ path: string; content: string; language?: string }>
    onProgress?: (phase: 'selecting-scaffold' | 'scaffolding' | 'customizing') => void
  },
): Promise<GeneratedProject> {
  if (config.provider === 'demo') return demoProject()

  const provider = createOpenAI({ baseURL: config.baseURL, apiKey: config.apiKey })
  input.onProgress?.('selecting-scaffold')
  const selectionResult = await generateText({
    model: provider(config.model),
    system: `${input.system}\n\nChoose exactly one deterministic scaffold tool before writing code. Available tools:\n${Object.entries(
      scaffoldToolDescriptions,
    )
      .map(([name, description]) => `- ${name}: ${description}`)
      .join(
        '\n',
      )}\nPrefer scaffold_webapp unless the user explicitly requests a CLI or backend API.`,
    messages: input.messages,
    maxOutputTokens: 1024,
    temperature: 0.2,
    tools: scaffoldTools,
    toolChoice: 'required',
  })

  input.onProgress?.('scaffolding')
  const scaffold = selectionResult.toolResults[0]?.output as ScaffoldProject | undefined
  if (!scaffold) throw new Error('The model did not select a scaffold tool')
  const baseFiles = input.existingFiles?.length ? [...input.existingFiles] : [...scaffold.files]
  if (!baseFiles.some((file) => file.path === '/openapi.yaml' || file.path === 'openapi.yaml')) {
    const contract = scaffold.files.find((file) => file.path === '/openapi.yaml')
    if (contract) baseFiles.push(contract)
  }
  input.onProgress?.('customizing')
  const result = await generateText({
    model: provider(config.model),
    system: `${input.system}\n\nA deterministic ${scaffold.kind} baseline has already been created. Modify it to satisfy the request. Return only files that must be added or replaced; unchanged baseline files are preserved automatically. Keep openapi.yaml synchronized with all HTTP-facing behavior. Use strict types, input validation, explicit error handling, accessible UI, tests where appropriate, pinned major versions, and no unresolved imports.\n\nBaseline files:\n${JSON.stringify(baseFiles)}`,
    messages: input.messages,
    maxOutputTokens: input.maxOutputTokens ?? 16384,
    temperature: 0.2,
    output: Output.object({
      schema: projectChangesSchema,
      name: 'project_changes',
      description: 'Focused file additions and replacements applied to the selected scaffold.',
    }),
  })

  const merged = new Map(baseFiles.map((file) => [file.path, file]))
  for (const changed of result.output.files) {
    const path = changed.path.startsWith('/') ? changed.path : `/${changed.path}`
    merged.set(path, { ...changed, path })
  }
  return {
    title: result.output.title,
    summary: result.output.summary,
    files: [...merged.values()],
    entrypoint: scaffold.entrypoint,
    template: scaffold.template,
  }
}

export function resolveModelProvider(
  env: NodeJS.ProcessEnv = process.env,
): ModelProviderConfig | null {
  const cloudflareAccountId = env.CLOUDFLARE_ACCOUNT_ID
  const cloudflareToken = env.CLOUDFLARE_API_TOKEN
  const requestedProvider = env.PAPYRUS_LLM_PROVIDER

  const useCloudflare =
    requestedProvider === 'cloudflare' ||
    (!requestedProvider && Boolean(cloudflareAccountId && cloudflareToken))

  if (useCloudflare) {
    if (!cloudflareAccountId || !cloudflareToken) return null
    return {
      provider: 'cloudflare-messages',
      baseURL:
        env.PAPYRUS_LLM_BASE_URL ??
        `https://api.cloudflare.com/client/v4/accounts/${cloudflareAccountId}/ai/v1`,
      apiKey: cloudflareToken,
      model: env.PAPYRUS_LLM_MODEL ?? 'thinkingmachines/inkling-256k',
    }
  }

  if (requestedProvider === 'demo') {
    return { provider: 'demo', baseURL: '', apiKey: '', model: 'demo-model' }
  }

  const apiKey = env.PAPYRUS_LLM_API_KEY ?? env.OPENROUTER_API_KEY ?? env.OPENAI_API_KEY
  if (!apiKey) return null
  const usingOpenRouter = Boolean(env.OPENROUTER_API_KEY) && !env.PAPYRUS_LLM_BASE_URL
  return {
    provider: 'openai-compatible',
    baseURL:
      env.PAPYRUS_LLM_BASE_URL ??
      (usingOpenRouter ? 'https://openrouter.ai/api/v1' : 'https://api.openai.com/v1'),
    apiKey,
    model: env.PAPYRUS_LLM_MODEL ?? (usingOpenRouter ? 'inclusionai/ling-3.0-tiny:free' : 'gpt-4o'),
  }
}

const DEMO_RESPONSES: Record<string, string> = {
  pm: `<artifact type="specification" title="Product Requirements Document">
# Product Requirements Document — Drone Asset Tracking Platform

## Vision
A peer-to-peer platform for real-time drone asset tracking across distributed teams in disconnected environments.

## User Stories
- **As a** field operator, **I want to** see all active drones on a map, **so that** I can monitor asset locations in real-time.
- **As a** mission commander, **I want to** receive alerts when drones deviate from planned routes, **so that** I can respond to anomalies.
- **As a** logistics coordinator, **I want to** generate utilization reports, **so that** I can optimize fleet allocation.

## Success Metrics
- 99.9% uptime for tracking data ingestion
- <2s latency for position updates
- Support for 500+ concurrent drone streams

## Requirements
1. Real-time GPS telemetry ingestion via MQTT
2. Offline-first architecture with CRDT sync
3. Role-based access control (RBAC)
4. Geofencing with configurable alert rules
</artifact>`,
  designer: `<artifact type="ui-mockup" title="Tracking Dashboard Wireframe">
{"schema":"papyrus.uswds-wireframe/v1","title":"UAS Marketplace","viewport":"desktop","description":"Federal marketplace discovery and onboarding dashboard","sections":[{"kind":"banner","text":"An official website of the United States government"},{"kind":"header","agency":"U.S. Army","title":"UAS Marketplace","navigation":["Marketplace","My requests","Vendors","Help"]},{"kind":"hero","eyebrow":"Commercial solutions","heading":"Find mission-ready UAS capabilities","body":"Search verified commercial systems, components, and enabling technologies available for evaluation.","primaryAction":"Browse capabilities","secondaryAction":"Submit a requirement"},{"kind":"search","label":"Search the UAS Marketplace","placeholder":"Search platforms, payloads, components, or vendors","buttonLabel":"Search"},{"kind":"card-grid","heading":"Featured capabilities","cards":[{"title":"Group 2 reconnaissance platform","body":"Modular ISR platform with government-defined interface documentation.","meta":"Assessment ready","action":"View capability"},{"title":"Navigation module","body":"Assured positioning component designed for contested environments.","meta":"Technical data available","action":"View capability"},{"title":"Payload integration kit","body":"Open interface kit for rapid sensor integration and evaluation.","meta":"New","action":"View capability"}]},{"kind":"summary-box","heading":"Need help defining a requirement?","body":"Start with a mission need and the marketplace team will help structure evaluation criteria.","items":["Describe the operational need","Identify constraints","Compare eligible capabilities"]},{"kind":"footer","agency":"U.S. Army","links":["Accessibility","Privacy","FOIA","Contact"]}]}
</artifact>`,
  engineer: `<artifact type="application" title="System Architecture">
# System Architecture

## Components
- **Ingestion Service** (Node.js) — MQTT broker subscriber, telemetry normalization
- **Sync Engine** (Rust) — CRDT-based state replication across nodes
- **API Gateway** (Go) — REST + WebSocket, RBAC enforcement
- **Storage** — SQLite (edge) / PostgreSQL (cloud), time-series telemetry
- **Web Client** (React) — XYFlow canvas, real-time map, offline support

## Data Flow
1. Drone → MQTT broker → Ingestion Service
2. Ingestion → Sync Engine → CRDT broadcast
3. Clients ← WebSocket ← API Gateway ← Sync Engine
4. Offline: Local SQLite outbox → flush on reconnect

## Security
- mTLS for all service-to-service communication
- Ed25519-signed operation bundles for cross-domain transfer
- AES-256-GCM encryption at rest
- SHA-256 hash-chained audit log
</artifact>`,
  security: `<artifact type="specification" title="Threat Model — Drone Tracking Platform">
# Threat Model

## Assets
- Real-time drone location data (classified up to SECRET)
- Fleet configuration and mission plans
- User credentials and RBAC policies

## Threat Actors
1. **Nation-state APT** — Targeted exfiltration of tracking data
2. **Insider threat** — Unauthorized access to mission plans
3. **Script kiddie** — Opportunistic scanning/exploitation

## Mitigations
- **Data exfiltration**: Cross-domain transfer allowlisting, signed bundles
- **Unauthorized access**: CAC/PIV + WebAuthn MFA, least-privilege RBAC
- **Network attacks**: mTLS, WAF, rate limiting (30 req/min/IP)
- **Supply chain**: Dependency pinning, SBOM generation, artifact signing

## Compliance
- FedRAMP Moderate baseline
- NIST 800-53 rev 5 controls
- IL4/IL6 deployment support via profile gating
</artifact>`,
}

const DEFAULT_DEMO_RESPONSE = `<artifact type="specification" title="Generated Artifact">
# Generated Content

Here is the generated artifact based on your request.

## Summary
This content was generated by the demo provider for Papyrus.

The system successfully routed your request to the appropriate persona agent and produced this structured output.
</artifact>`

export function getDemoResponse(persona: string): string {
  return DEMO_RESPONSES[persona] ?? DEFAULT_DEMO_RESPONSE
}

export async function generateModelText(
  config: ModelProviderConfig,
  input: {
    system: string
    messages: ModelMessage[]
    temperature?: number
    maxOutputTokens?: number
  },
): Promise<string> {
  if (config.provider === 'demo') {
    // Extract persona from system prompt
    const systemLower = input.system.toLowerCase()
    let persona = 'pm'
    if (systemLower.includes('designer')) persona = 'designer'
    else if (systemLower.includes('engineer')) persona = 'engineer'
    else if (systemLower.includes('security')) persona = 'security'
    const response = getDemoResponse(persona)
    // Simulate streaming delay
    await new Promise((r) => setTimeout(r, 800 + Math.random() * 1200))
    return response
  }

  if (config.provider === 'cloudflare-messages') {
    const response = await fetch(`${config.baseURL.replace(/\/$/, '')}/messages`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${config.apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: config.model,
        system: input.system,
        messages: input.messages,
        max_tokens: input.maxOutputTokens ?? 4096,
        temperature: input.temperature ?? 0.7,
      }),
    })
    const responseBody = (await response.json()) as {
      content?: Array<{ type?: string; text?: string }>
      errors?: Array<{ message?: string }>
      error?: { message?: string }
      result?: {
        content?: Array<{ type?: string; text?: string }>
      }
    }
    if (!response.ok) {
      throw new Error(
        responseBody.errors
          ?.map((error) => error.message)
          .filter(Boolean)
          .join('; ') ||
          responseBody.error?.message ||
          `Cloudflare Workers AI request failed (${response.status})`,
      )
    }
    const body = responseBody.result ?? responseBody
    const text = body.content
      ?.filter((block) => block.type === 'text')
      .map((block) => block.text ?? '')
      .join('\n')
      .trim()
    if (!text) throw new Error('Cloudflare Workers AI returned no text content')
    return text
  }

  const provider = createOpenAI({ baseURL: config.baseURL, apiKey: config.apiKey })
  const result = await generateText({
    model: provider(config.model),
    system: input.system,
    messages: input.messages,
    temperature: input.temperature ?? 0.7,
    maxOutputTokens: input.maxOutputTokens ?? 4096,
  })
  return result.text
}

export interface StreamCallbacks {
  onToken: (token: string) => void
  onComplete: (fullText: string) => void
  onError: (error: Error) => void
}

export async function generateModelTextStream(
  config: ModelProviderConfig,
  input: {
    system: string
    messages: ModelMessage[]
    temperature?: number
    maxOutputTokens?: number
  },
  callbacks: StreamCallbacks,
): Promise<void> {
  if (config.provider === 'demo') {
    const systemLower = input.system.toLowerCase()
    let persona = 'pm'
    if (systemLower.includes('designer')) persona = 'designer'
    else if (systemLower.includes('engineer')) persona = 'engineer'
    else if (systemLower.includes('security')) persona = 'security'
    const response = getDemoResponse(persona)
    const words = response.split(/(?<=\s)/)
    let full = ''
    for (const word of words) {
      full += word
      callbacks.onToken(word)
      await new Promise((r) => setTimeout(r, 15 + Math.random() * 25))
    }
    callbacks.onComplete(full)
    return
  }

  if (config.provider === 'cloudflare-messages') {
    // Cloudflare doesn't support streaming via the messages API — fall back to non-streaming
    const full = await generateModelText(config, input)
    callbacks.onToken(full)
    callbacks.onComplete(full)
    return
  }

  const provider = createOpenAI({ baseURL: config.baseURL, apiKey: config.apiKey })
  const result = streamText({
    model: provider(config.model),
    system: input.system,
    messages: input.messages,
    temperature: input.temperature ?? 0.7,
    maxOutputTokens: input.maxOutputTokens ?? 4096,
  })

  let full = ''
  for await (const delta of result.textStream) {
    full += delta
    callbacks.onToken(delta)
  }
  callbacks.onComplete(full)
}
