import type { NodeTypeSpec } from '../types.js'

/** Design nodes — represent design work. Review nodes gate the flow. */
export const DESIGN_NODES: NodeTypeSpec[] = [
  {
    type: 'workflow',
    category: 'design',
    flowRole: 'artifact',
    icon: 'flow',
    title: 'Workflow',
    description: 'A sequence of steps accomplishing a task.',
    fields: [{ key: 'steps', label: 'Steps', type: 'json' }],
  },
  {
    type: 'service-blueprint',
    category: 'design',
    flowRole: 'artifact',
    icon: 'blueprint',
    title: 'Service Blueprint',
    description: 'Map of front-stage, back-stage, and support processes.',
    fields: [{ key: 'steps', label: 'Steps', type: 'json' }],
  },
  {
    type: 'information-architecture',
    category: 'design',
    flowRole: 'artifact',
    icon: 'tree',
    title: 'Information Architecture',
    description: 'Structuring of information and navigation.',
    fields: [{ key: 'tree', label: 'Tree', type: 'json' }],
  },
  {
    type: 'wireframe',
    category: 'design',
    flowRole: 'artifact',
    icon: 'frame',
    title: 'Wireframe',
    description: 'Low-fidelity layout sketch.',
    fields: [
      { key: 'artifact', label: 'Artifact', type: 'blob' },
      { key: 'annotations', label: 'Annotations', type: 'markdown' },
    ],
  },
  {
    type: 'screen',
    category: 'design',
    flowRole: 'artifact',
    icon: 'monitor',
    title: 'Screen',
    description: 'A designed screen / view.',
    fields: [
      { key: 'artifact', label: 'Artifact', type: 'blob' },
      { key: 'annotations', label: 'Annotations', type: 'markdown' },
    ],
  },
  {
    type: 'component',
    category: 'design',
    flowRole: 'artifact',
    icon: 'puzzle',
    title: 'Component',
    description: 'A reusable UI component.',
    fields: [
      { key: 'artifact', label: 'Artifact', type: 'blob' },
      { key: 'annotations', label: 'Annotations', type: 'markdown' },
    ],
  },
  {
    type: 'accessibility-review',
    category: 'design',
    flowRole: 'review',
    icon: 'universal',
    title: 'Accessibility Review',
    description: 'WCAG-based accessibility review. Gates the flow on approval.',
    reviewable: true,
    fields: [
      { key: 'scope', label: 'Scope', type: 'ref', refType: 'screen', multi: true },
      { key: 'wcagCriteria', label: 'WCAG Criteria', type: 'list', multi: true },
      { key: 'findings', label: 'Findings', type: 'markdown' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'passed', 'failed'] },
    ],
  },
  {
    type: 'usability-test',
    category: 'design',
    flowRole: 'review',
    icon: 'users-test',
    title: 'Usability Test',
    description: 'Planned usability test with findings.',
    reviewable: true,
    fields: [
      { key: 'scope', label: 'Scope', type: 'text' },
      { key: 'findings', label: 'Findings', type: 'markdown' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'passed', 'failed'] },
    ],
  },
  {
    type: 'design-review',
    category: 'design',
    flowRole: 'review',
    icon: 'eye-check',
    title: 'Design Review',
    description: 'Peer design review gate.',
    reviewable: true,
    fields: [
      { key: 'scope', label: 'Scope', type: 'text' },
      { key: 'findings', label: 'Findings', type: 'markdown' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'passed', 'failed'] },
    ],
  },
]
