import type { NodeTypeSpec } from '../types.js'

/**
 * Engineering nodes — implementation artifacts. Security Review and Threat
 * Model are `review` gates (HITL). The rest are `artifact`.
 */
export const ENGINEERING_NODES: NodeTypeSpec[] = [
  {
    type: 'architecture',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'building',
    title: 'Architecture',
    description: 'System architecture description and diagram.',
    fields: [
      { key: 'description', label: 'Description', type: 'markdown', required: true },
      { key: 'diagram', label: 'Diagram', type: 'blob' },
    ],
  },
  {
    type: 'infrastructure',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'server',
    title: 'Infrastructure',
    description: 'Infrastructure definition (IaC, topology).',
    fields: [
      { key: 'description', label: 'Description', type: 'markdown' },
      { key: 'artifact', label: 'Artifact', type: 'blob' },
    ],
  },
  {
    type: 'deployment',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'rocket',
    title: 'Deployment',
    description: 'Deployment process and topology.',
    fields: [{ key: 'description', label: 'Description', type: 'markdown' }],
  },
  {
    type: 'api',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'plug',
    title: 'API',
    description: 'An API contract (OpenAPI).',
    fields: [
      { key: 'spec', label: 'OpenAPI Spec', type: 'schema', schemaRef: 'openapi', required: true },
      { key: 'version', label: 'Version', type: 'text' },
    ],
  },
  {
    type: 'data-model',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'diagram',
    title: 'Data Model',
    description: 'Entity and relationship model.',
    fields: [{ key: 'spec', label: 'Spec', type: 'json', required: true }],
  },
  {
    type: 'database',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'database',
    title: 'Database',
    description: 'Database selection and configuration.',
    fields: [{ key: 'description', label: 'Description', type: 'markdown' }],
  },
  {
    type: 'schema',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'table',
    title: 'Schema',
    description: 'A data schema definition.',
    fields: [{ key: 'spec', label: 'Spec', type: 'json', required: true }],
  },
  {
    type: 'integration',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'link',
    title: 'Integration',
    description: 'An external system integration.',
    fields: [{ key: 'description', label: 'Description', type: 'markdown' }],
  },
  {
    type: 'security-review',
    category: 'engineering',
    flowRole: 'review',
    icon: 'shield',
    title: 'Security Review',
    description: 'Security review gate (e.g. for Authority to Operate).',
    reviewable: true,
    fields: [
      { key: 'scope', label: 'Scope', type: 'text', required: true },
      {
        key: 'framework',
        label: 'Framework',
        type: 'select',
        options: ['rmf', 'nist-800-53', 'cis'],
      },
      { key: 'findings', label: 'Findings', type: 'markdown' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'passed', 'failed'] },
    ],
  },
  {
    type: 'threat-model',
    category: 'engineering',
    flowRole: 'review',
    icon: 'ghost',
    title: 'Threat Model',
    description: 'Threat model (STRIDE, attack tree, LIN, DREAD).',
    reviewable: true,
    fields: [
      {
        key: 'framework',
        label: 'Framework',
        type: 'select',
        options: ['stride', 'attack-tree', 'lin', 'dread'],
        required: true,
      },
      { key: 'threats', label: 'Threats', type: 'json' },
      { key: 'mitigations', label: 'Mitigations', type: 'json' },
    ],
  },
  {
    type: 'technical-debt',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'trash',
    title: 'Technical Debt',
    description: 'A recorded tech-debt item and remediation plan.',
    fields: [
      { key: 'item', label: 'Item', type: 'text', required: true },
      { key: 'impact', label: 'Impact', type: 'text' },
      { key: 'plan', label: 'Plan', type: 'markdown' },
    ],
  },
  {
    type: 'test-plan',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'list-check',
    title: 'Test Plan',
    description: 'What will be tested and how.',
    fields: [
      { key: 'scope', label: 'Scope', type: 'markdown', required: true },
      { key: 'steps', label: 'Steps', type: 'list', multi: true },
    ],
  },
  {
    type: 'test-case',
    category: 'engineering',
    flowRole: 'artifact',
    icon: 'check-square',
    title: 'Test Case',
    description: 'A discrete test case with expected result.',
    fields: [
      { key: 'scope', label: 'Scope', type: 'text' },
      { key: 'steps', label: 'Steps', type: 'list', multi: true },
      { key: 'expected', label: 'Expected', type: 'text' },
    ],
  },
]
