import type { NodeTypeSpec } from '../types.js'

/**
 * Discovery nodes — capture and synthesize customer understanding.
 * Mostly `source` (entry) or `artifact`. Shipped-first (✓) types are
 * implemented for the canvas palette in P0–P3; the rest are catalog entries.
 */
export const DISCOVERY_NODES: NodeTypeSpec[] = [
  {
    type: 'mission-need',
    category: 'discovery',
    flowRole: 'source',
    icon: 'flag',
    title: 'Mission Need',
    description: 'The operational gap or mission shortfall to be addressed.',
    fields: [
      { key: 'statement', label: 'Mission Need Statement', type: 'markdown', required: true },
      { key: 'sponsor', label: 'Sponsor', type: 'ref', refType: 'stakeholder' },
      {
        key: 'priority',
        label: 'Priority',
        type: 'select',
        options: ['low', 'med', 'high', 'critical'],
      },
      {
        key: 'impactLevel',
        label: 'Impact Level',
        type: 'select',
        options: ['il2', 'il4', 'il5', 'il6'],
      },
    ],
  },
  {
    type: 'problem-statement',
    category: 'discovery',
    flowRole: 'source',
    icon: 'alert',
    title: 'Problem Statement',
    description: 'Concise statement of the problem, grounded in evidence.',
    fields: [
      { key: 'statement', label: 'Statement', type: 'markdown', required: true },
      { key: 'evidence', label: 'Evidence', type: 'ref', refType: 'insight', multi: true },
    ],
  },
  {
    type: 'opportunity',
    category: 'discovery',
    flowRole: 'source',
    icon: 'sparkle',
    title: 'Opportunity',
    description: 'A potential area for improvement or innovation.',
    fields: [{ key: 'summary', label: 'Summary', type: 'markdown', required: true }],
  },
  {
    type: 'stakeholder',
    category: 'discovery',
    flowRole: 'source',
    icon: 'user',
    title: 'Stakeholder',
    description: 'An individual or group with interest in the outcome.',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'org', label: 'Organization', type: 'text' },
      { key: 'influence', label: 'Influence', type: 'select', options: ['low', 'med', 'high'] },
    ],
  },
  {
    type: 'persona',
    category: 'discovery',
    flowRole: 'artifact',
    icon: 'mask',
    title: 'Persona',
    description: 'A representative user archetype.',
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'role', label: 'Role', type: 'text' },
      { key: 'demographics', label: 'Demographics', type: 'json' },
      { key: 'goals', label: 'Goals', type: 'list', multi: true },
      { key: 'frustrations', label: 'Frustrations', type: 'list', multi: true },
    ],
  },
  {
    type: 'jobs-to-be-done',
    category: 'discovery',
    flowRole: 'artifact',
    icon: 'wrench',
    title: 'Jobs to Be Done',
    description: 'The job a user is hiring the product to do.',
    fields: [
      { key: 'situation', label: 'Situation', type: 'text', required: true },
      { key: 'motivation', label: 'Motivation', type: 'text' },
      { key: 'expectedOutcome', label: 'Expected Outcome', type: 'text' },
    ],
  },
  {
    type: 'user-journey',
    category: 'discovery',
    flowRole: 'artifact',
    icon: 'route',
    title: 'User Journey',
    description: 'End-to-end sequence of user steps and touchpoints.',
    fields: [{ key: 'stages', label: 'Stages', type: 'json' }],
  },
  {
    type: 'journey-map',
    category: 'discovery',
    flowRole: 'artifact',
    icon: 'map',
    title: 'Journey Map',
    description: 'Visual map of the user journey with emotions and touchpoints.',
    fields: [
      { key: 'stages', label: 'Stages', type: 'json' },
      { key: 'diagram', label: 'Diagram', type: 'blob' },
    ],
  },
  {
    type: 'ethnographic-observation',
    category: 'discovery',
    flowRole: 'source',
    icon: 'eye',
    title: 'Ethnographic Observation',
    description: 'A field observation of users in context.',
    fields: [
      { key: 'observation', label: 'Observation', type: 'markdown', required: true },
      { key: 'context', label: 'Context', type: 'text' },
      { key: 'date', label: 'Date', type: 'text' },
    ],
  },
  {
    type: 'interview',
    category: 'discovery',
    flowRole: 'source',
    icon: 'microphone',
    title: 'Interview',
    description: 'A stakeholder or user interview with transcript.',
    fields: [
      { key: 'subject', label: 'Subject', type: 'ref', refType: 'stakeholder' },
      { key: 'transcript', label: 'Transcript', type: 'blob' },
      { key: 'notes', label: 'Notes', type: 'markdown' },
    ],
  },
  {
    type: 'survey',
    category: 'discovery',
    flowRole: 'source',
    icon: 'clipboard',
    title: 'Survey',
    description: 'A structured survey and its responses.',
    fields: [
      { key: 'questions', label: 'Questions', type: 'json' },
      { key: 'responses', label: 'Responses', type: 'blob' },
    ],
  },
  {
    type: 'feedback',
    category: 'discovery',
    flowRole: 'source',
    icon: 'message',
    title: 'Feedback',
    description: 'User or stakeholder feedback.',
    fields: [{ key: 'body', label: 'Feedback', type: 'markdown', required: true }],
  },
  {
    type: 'pain-point',
    category: 'discovery',
    flowRole: 'artifact',
    icon: 'fire',
    title: 'Pain Point',
    description: 'A specific user pain point.',
    fields: [
      { key: 'description', label: 'Description', type: 'markdown', required: true },
      { key: 'severity', label: 'Severity', type: 'select', options: ['low', 'med', 'high'] },
      { key: 'evidence', label: 'Evidence', type: 'ref', refType: 'insight', multi: true },
    ],
  },
  {
    type: 'insight',
    category: 'discovery',
    flowRole: 'artifact',
    icon: 'bulb',
    title: 'Insight',
    description: 'A synthesized insight from research.',
    fields: [{ key: 'description', label: 'Insight', type: 'markdown', required: true }],
  },
  {
    type: 'assumption',
    category: 'discovery',
    flowRole: 'artifact',
    icon: 'question',
    title: 'Assumption',
    description: 'A belief assumed true until validated.',
    fields: [
      { key: 'statement', label: 'Assumption', type: 'text', required: true },
      { key: 'validation', label: 'Validation', type: 'ref', refType: 'experiment' },
    ],
  },
  {
    type: 'hypothesis',
    category: 'discovery',
    flowRole: 'artifact',
    icon: 'flask',
    title: 'Hypothesis',
    description: 'A testable hypothesis.',
    fields: [
      { key: 'statement', label: 'Hypothesis', type: 'text', required: true },
      { key: 'validation', label: 'Validation', type: 'ref', refType: 'experiment' },
    ],
  },
  {
    type: 'risk',
    category: 'discovery',
    flowRole: 'artifact',
    icon: 'warning',
    title: 'Risk',
    description: 'A programmatic or technical risk.',
    fields: [
      { key: 'description', label: 'Description', type: 'markdown', required: true },
      { key: 'likelihood', label: 'Likelihood', type: 'select', options: ['low', 'med', 'high'] },
      { key: 'impact', label: 'Impact', type: 'select', options: ['low', 'med', 'high'] },
      { key: 'mitigation', label: 'Mitigation', type: 'markdown' },
    ],
  },
  {
    type: 'constraint',
    category: 'discovery',
    flowRole: 'artifact',
    icon: 'lock',
    title: 'Constraint',
    description: 'A binding constraint on the solution space.',
    fields: [{ key: 'description', label: 'Description', type: 'markdown', required: true }],
  },
]
